
services:
  server:
    entrypoint: ./entrypoint.sh
    build: .
    restart: unless-stopped
    environment:
      TZ: "Asia/Calcutta"
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: journalia
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - journalia_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: journalia@journalia.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - journalia_pgadmin:/var/lib/pgadmin
    logging:
      driver: none

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - journalia_redis:/data

volumes:
  journalia_db:
  journalia_pgadmin:
  journalia_redis:
